# Generated by Django 2.2.13 on 2022-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220203_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='file',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, height_field='50', upload_to='.', width_field='100'),
        ),
    ]
