# Generated by Django 2.2.13 on 2022-02-03 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220203_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_likes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 12, 56, 10, 422289)),
        ),
    ]
