# Generated by Django 2.2.13 on 2022-02-03 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220203_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_likes',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_likes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 14, 14, 16, 932435)),
        ),
    ]
