# Generated by Django 2.2.13 on 2022-02-03 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220203_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_likes',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='post_likes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 14, 17, 48, 4350)),
        ),
    ]
