# Generated by Django 2.2.13 on 2022-02-03 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220203_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_likes',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 14, 19, 17, 252553)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post_likes'),
        ),
    ]
